import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import { Theme } from "@/components/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" data-theme="app">
      <body className={`${inter.className}`}>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
