version: "3"

services:
  # Postgres service configuration
  postgresql:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_USER: user_betashop
      POSTGRES_PASSWORD: c8596sgw
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - my-network

  # API service configuration
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8686:8686"
    volumes:
      - .:/usr/app
    networks:
      - my-network
    depends_on:
      - postgresql

networks:
  my-network:
